---
title: "Lesson 13: Wrapping up and looking ahead"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Today is our last class!
Course evaluations will be available from tomorrow May 5th and until May 23rd. Students formally enrolled should get an email with a link to the evaluation. Participants who are  I will 

This was the first time I have offered this course, so your feedback

I’m hoping to be able to offer it in person next time, so while feedback on how the online format worked out certainly 

Completely anonymous and I only get to see it after S/U decisions have been submitted.


## Agenda for today's class

* Review of good practices / mindset for moving forward
* Strategies for trouble-shooting and de-bugging
* Where and how to get help and connect with the R user community
* Where to learn more

<br>

## Good practices

#### 1. Keep your raw data raw

#### 2. Frequently test that your code can run in a new environment
nuke your session and run from the top. It should still work.
Don’t save workspace upon closing.
project-oriented workflow https://www.tidyverse.org/blog/2017/12/workflow-vs-script/

If the thought of re-running your analysis makes you ill, you're not doing it right
https://www.slideshare.net/jenniferbryan5811/cm002-deep-thoughts

#### 3. Work in R projects within RStudio
https://www.tidyverse.org/blog/2017/12/workflow-vs-script/

#### 4. Explain and document your thought process with notes and comments
document the big-picture structure both within files (comments) and between files (README’s).
An unsuspecting data scientist stumbles upon your work. Can they figure out what’s going on?

#### 5. Develop a consistent coding style that maximizes readability
Style guide
http://adv-r.had.co.nz/Style.html
https://style.tidyverse.org/index.html
There are also great tips for styling, organizing and optimizing your code in the blogpost [R Best Practices: R you writing the R way!](https://blog.quantinsti.com/r-best-practices-r-you-writing-the-r-way/?utm_campaign=News&utm_medium=Community&utm_source=DataCamp.com) by Milind Paradkar
Many of the same principles are also summarized by JEFworks [here](https://jef.works/R-style-guide/)

#### 6. "Write code for humans, write data for computers"
Very important advice from [Vince Buffalo](https://twitter.com/vsbuffalo/status/358699162679787521) 



<br>


## Trouble-shooting and de-bugging


Get into the mindset
> Getting help, or really helping you help yourself, means moving beyond “it’s not working” and towards solution-oriented approaches. Part of this is the mindset where you expect that someone has encountered this problem before and that most likely the problem is your typo or misuse, and not that R is broken or hates you.



[ESM Lecture 2 - by Allison Horst](https://docs.google.com/presentation/d/1u1DdhU_WTv1b-sbQgqVGAE-bA2Nq_Yym8BzcPW4lS3k/edit#slide=id.g619be0f969_0_27)

Jenny Bryan trouble-shooting?
check out slides https://resources.rstudio.com/rstudio-conf-2020/object-of-type-closure-is-not-subsettable-jenny-bryan
or recorded talk
https://speakerdeck.com/jennybc/object-of-type-closure-is-not-subsettable?slide=12

> "Don't wring hands and speculate. Work on a small concrete example that reveals, confirms or eliminates something" Jenny Bryan [on creating a reprex]

This step involves making the problem as small as possible, which is known as making a “minimally reproducible example” or a “reprex.” In making a reprex, you should isolate what is happening, using as little information as possible. So if it’s a ggplot question, for example, make a toy data frame with the minimum number of rows and columns to reproduce the behavior. For more complete information on making a reprex, watch Jenny Bryan’s webinar on the reprex package.

[Reprex webinar](https://resources.rstudio.com/webinars/help-me-help-you-creating-reproducible-examples-jenny-bryan) - by Jenny Bryan

Tips on how to start engaging on twitter https://rstudio-conf-2020.github.io/r-for-excel/collaborating.html#r-communities

and

https://github.com/jthomasmock/presentations/blob/master/r-community2.pdf
Imposter syndrome slide


<br>

## Resources for learning more

#### R and the tidyverse

* [R for Data Science](https://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham. See also answers to the exercises [here](https://jrnold.github.io/r4ds-exercise-solutions/) and other places you can find on google and a dedicated [Slack workspace](https://www.rfordatasci.com/) for community learning.
* [Advanced R](https://adv-r.hadley.nz/) by Hadley Wickham
* [swirl: learn R, in R](https://swirlstats.com/)
* [What they forgot to teach you about R](https://github.com/rstats-wtf/what-they-forgot) by Jenny Bryan and Jim Hester
* [Course notes for STAT545](https://stat545.com/) by Jenny Bryan
* [Practical Data Science for Stats - a PeerJ Collection](https://peerj.com/collections/50-practicaldatascistats/)
* [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/) by Hadley Wickham

Tidy Tuesday

Here are a few other books you might want to check out:
https://moderndive.com/
https://rc2e.com/
https://rafalab.github.io/dsbook/


#### RMarkdown

* [RMarkdown for Scientists](https://rmd4sci.njtierney.com/) by Nicholas Tierney
* [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) by Yihui Xie, J. J. Allaire, and Garrett Grolemund

#### GitHub
* [Happy Git and GitHub for the useR](https://happygitwithr.com/) by Jenny Bryan

<br>

#### More cool R applications

**Dashboards:**

Check out the [Dashboard](https://ramikrispin.github.io/coronavirus_dashboard/#summary) developed for the continually updated Coronavirus dataset we worked with earlier in the course. Note that you can grab all the code under `Source code` in the top right corner.

Dashboards can also be made interactive with dynamic and user-controlled displays of data through use of [Shiny](https://shiny.rstudio.com/), an R package that makes it easy to build interactive web apps straight from R.

For an example, check out [this dynamic visualization](https://uomresearchit.github.io/r-shiny-course/) of the gapminder dataset we worked with in our last class (make sure to check out the [cool video](https://www.youtube.com/watch?v=jbkSRLYSojo) with Hans Rosling) 

[Here](https://rebjoh.shinyapps.io/Gapminder-app/) is a much simpler shiny app with interactive display of the same data.

For more examples, check out the [RStudio Flexdashboard website](https://rmarkdown.rstudio.com/flexdashboard/)

And check out [Mastering shiny](https://mastering-shiny.org/) by Hadley Wickham


<br>

## Take-homes

http://ohi-science.org/data-science-training/champion.html#three-messages


## Discussion questions

* What is the most valuable thing you have learned in this class?
* Are you planning to implement any changes your workflow or practices moving forward
* What are you excited about learning next or what existing skills do you want to improve?

